name: Deploy Nightly
on:
  sechedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  nightly:
    name: Deploy Nightly
    runs-on: ubuntu-latest
    steps:
      # Install tools
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      # Build
      - name: Install
        run: pnpm install
      
      - name: Build
        run: pnpm run build

      # Create asset
      - name: Make data
        run: node dist/index.js